
services:
  db:
    image: postgres:14
    container_name: wallet_postgres
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - wallet_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  app:
    build: .
    container_name: wallet_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://wallet:wallet@db:5432/wallet_db

volumes:
  wallet_data:
