
services:
  db:
    image: postgres:14
    container_name: wallet_postgres
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - wallet_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  wallet_data:
